### ISSUE TITLE
What does `BIG_ENDIAN` do in fpu.h

### ISSUE THREAD

**Issue by DCNick3** [nepx/halfix#4]
I'm not sure what does ifdef with a `BIG_ENDIAN` does. Is it an attemt to support arbitrary endianness hosts? Well, if it is, then it does not work. Even if standard C had something like that, at my perfectly little endian x86_64 system it is defined somewhere in depths of glibc...

**Comment by nepx** [comment]
Hello, 

This emulator uses the SoftFloat package from Bochs, which handles big-endian data better than I do: 

```c
/*----------------------------------------------------------------------------
| Software IEC/IEEE floating-point types.
*----------------------------------------------------------------------------*/

#ifdef BX_BIG_ENDIAN
typedef struct {	// leave alignment to compiler
    uint16_t exp;
    uint64_t fraction;
} floatx80;
#else
typedef struct {
    uint64_t fraction;
    uint16_t exp;
} floatx80;
#endif
```

Aliasing the MMX registers to the FP stack was a hack involving a union (but it works, so there's that!), and I had to make sure that both registers were laid out the same way (replacing `fraction` for `r8`. `r16`, etc.). Rather than `BX_BIG_ENDIAN`, I went with the simpler `BIG_ENDIAN`. 

The fact that `BIG_ENDIAN` is defined on x86-64 systems is a good point (and a slightly strange one, too, considering that x86-64 is a little-endian system) and something that definitely needs to be fixed, but in practice it's never caused me any trouble. 

Concerning endianness: big endian hosts might work, but I doubt they do. Reworking the emulator to handle guest loads/stores would be a massive multi-month project, but sadly I don't have any big-endian systems to debug on. At the very least, all those crazy `arith_rmw` macros in `opcodes.c` will need to be reworked.
